import Head from 'next/head';
import { Inter } from '@next/font/google';
import Footer from '../components/Footer';
import Frame from '../components/Frame';
import BtnPrimary from '../components/BtnPrimary';
import Navbar from '../components/Navbar';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
    return (
        <>
            <Head>
                <title>Home</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <meta
                    name='viewport'
                    content='width=device-width, initial-scale=1'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>

            <Frame>
                <Navbar />

                <div className='flex flex-col justify-center items-center min-h-screen mobile:-mt-20 tablet:-mt-10 -mb-10'>
                    <div className='text-center'>
                        <h1 className='text-xl tablet:text-2xl text-accent font-bold inter'>
                            HELLO THERE!
                        </h1>
                        <p className='text-4xl tablet:text-6xl font-bold inter text-white mt-4'>
                            Im a Front-End Developer
                        </p>
                        <p className='text-sm tablet:text-base font-light inter italic text-[#A9A9A9] mt-3'>
                            Based on Surabaya, Indonesia
                        </p>
                    </div>
                    <div className='flex justify-center mt-12 relative'>
                        <BtnPrimary href='/contact'>Hire me now!</BtnPrimary>
                    </div>
                </div>

                <Footer />
            </Frame>
        </>
    );
}
