/* eslint-disable @next/next/no-img-element */
import Head from 'next/head';
import React from 'react';
import Footer from '../components/Footer';
import Frame from '../components/Frame';
import Navbar from '../components/Navbar';
import BtnPrimary from '../components/BtnPrimary';
import BtnOutline from '../components/BtnOutline';
import Image from 'next/image';
import { AppProvider } from '../context/app.context';
import CardProject from '../components/CardProject';

export default function project() {
    return (
        <>
            <Head>
                <title>Projects</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <meta
                    name='viewport'
                    content='width=device-width, initial-scale=1'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <Frame>
                <Navbar />

                <div className='my-20'>
                    <h2 className='text-xl tablet:text-2xl text-accent font-bold inter'>
                        MY PROJECTS
                    </h2>
                    <h1 className='text-4xl text-white font-bold inter mt-6'>
                        This is a collection of projects that I have created
                    </h1>

                    <AppProvider>
                        <CardProject />
                    </AppProvider>

                    <div className='flex justify-center mt-12 relative'>
                        <BtnPrimary className='w-64' href='#'>
                            See all projects
                        </BtnPrimary>
                    </div>
                    <div className='flex justify-center mt-4 relative'>
                        <BtnOutline className='w-64' href='#'>
                            Add New Project
                        </BtnOutline>
                    </div>
                </div>

                <Footer />
            </Frame>
        </>
    );
}
